In [14]:
import numpy as np

def MAT_OP(A, B):
    """矩阵最小传递 O(n^3)"""
    n = len(A)
    C = np.zeros((n, n))
    for i, j in np.ndindex(n, n): # O(n^2)
        C[i, j] = np.inf
        for k in range(n): # O(n)
            C[i, j] = min(C[i, j], A[i, k] + B[k, j])
    return C

def SLOW_ALL_PAIRS_SHORTEST_PATHS(W):
    n = len(W)
    L = W.copy()
    for m in range(2, n): # O(n)
        L = MAT_OP(L, W)
    return L

def FASTER_ALL_PAIRS_SHORTEST_PATHS(W):
    """矩阵幂"""
    n = len(W)
    L = W.copy()
    m = 1
    while m < n - 1: # O(lgn)
        L = MAT_OP(L, L)
        m *= 2
    return L

In [15]:
W = np.array(
    [
        [0, 3, 8, np.inf, -4],
        [np.inf, 0, np.inf, 1, 7],
        [np.inf, 4, 0, np.inf, np.inf],
        [2, np.inf, -5, 0, np.inf],
        [np.inf, np.inf, np.inf, 6, 0],
    ]
)
print(SLOW_ALL_PAIRS_SHORTEST_PATHS(W))
print(FASTER_ALL_PAIRS_SHORTEST_PATHS(W))

[[ 0.  1. -3.  2. -4.]
 [ 3.  0. -4.  1. -1.]
 [ 7.  4.  0.  5.  3.]
 [ 2. -1. -5.  0. -2.]
 [ 8.  5.  1.  6.  0.]]
[[ 0.  1. -3.  2. -4.]
 [ 3.  0. -4.  1. -1.]
 [ 7.  4.  0.  5.  3.]
 [ 2. -1. -5.  0. -2.]
 [ 8.  5.  1.  6.  0.]]
